[hooks]
preinstall = "echo installing"
postinstall = "echo done installing"
enter = "mise install"
leave = "echo left ${MISE_PREVIOUS_DIR}"

[tools]
github-cli = "latest"
go = "1.24.2"
gofumpt = "latest"
golangci-lint = "2"
golangci-lint-langserver = "latest"
golines = "latest"
gotestsum = "latest"
just = "latest"

"go:golang.org/x/tools/cmd/deadcode" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:go.uber.org/mock/mockgen" = "latest"
