[tools]
github-cli = "latest"
go = "1.24"
gofumpt = "0.9.1"
golangci-lint = "2"
golangci-lint-langserver = "latest"
golines = "latest"
gotestsum = "latest"
hk = "latest"
just = "latest"
pkl = "latest"

"go:go.uber.org/mock/mockgen" = "latest"
"go:golang.org/x/perf/cmd/benchstat" = "latest"
"go:golang.org/x/tools/cmd/benchcmp" = "latest"
"go:golang.org/x/tools/cmd/deadcode" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"

[[hooks.enter]]
script = "mise install"
[[hooks.enter]]
script = "hk install"

[tasks.build]
run = "go build -v ./..."
[tasks.test]
run = "gotestsum -f dots -- -race -coverprofile cover.out -count 1 ./..."
[tasks.vtest]
run = "go test -v -race -coverprofile cover.out -count 1 ./..."
[tasks.cover]
run = "go tool cover -html cover.out -o cover.html"
[tasks.check]
run = "hk run check"
[tasks.fix]
run = "hk run fix"
