name: Go

on:
  push:
    branches: [main, master]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [stable, oldstable]
        include:
          - go: stable
            golangci: v1.58
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race -coverprofile cover.out ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        if: matrix.golangci
        with:
          version: ${{ matrix.golangci }}

      - name: Prepare Coverage
        run: go tool cover -html cover.out -o cover.html

      - name: Upload Coverage
        uses: codecov/codecov-action@v4
